"""Generate docs/pagoda_warren/ROUTES.md — a markdown catalogue of every Pagoda
Warren route, with its tier, 1-10 difficulty rating, what it teaches, and length.
Pulled straight from the route scripts so it stays in sync. No game/ files touched.

    PYTHONPATH=. python tools/gen_routes_md.py
"""
import os

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

import pygame
pygame.init()

from tools.render_warren_all import TIERS, get_pagodas

FIG = "https://github.com/ytocker/skybit/blob/v5_skybit_enrich/docs/pagoda_warren"
FIGURES = [
    ("All routes, rated by difficulty", "routes_all.png"),
    ("Base — 10 teaching routes", "routes.png"),
    ("Advanced — 10 creative routes", "routes_advanced.png"),
    ("Serious drop — 5 routes", "routes_drops.png"),
    ("Aggressive drop — 5 routes", "routes_drops_aggressive.png"),
    ("Smaller drop — 5 skilled-but-fair routes", "routes_drops_smaller.png"),
]


def main():
    # Collect rows: (rating, name, tier, lesson, n, duration)
    tiers_data = []
    all_rows = []
    for tier, build, ratings in TIERS:
        routes = build()
        rows = []
        for route, d in zip(routes, ratings):
            pg = get_pagodas(route)
            rows.append((d, route.name, route.lesson, route.n, route.duration))
            all_rows.append((d, route.name, tier))
        tiers_data.append((tier, rows))

    lines = []
    A = lines.append
    A("# Pagoda Warren — Route Catalogue\n")
    A("All gameplay routes designed for the **Pagoda Warren** event — the fused "
      "pagoda corridor the parrot threads. Each route is one continuous stretch "
      "(~0.45s per pagoda) authored to teach or test a specific one-button "
      "maneuver, and is checked against the warren's passability rules. Every "
      "route uses the approved Gentle-Sine-Tube pagoda look.\n")
    A(f"**{len(all_rows)} routes** across five tiers, rated **1–10** for "
      "challenge.\n")

    A("## Figures\n")
    for title, fname in FIGURES:
        A(f"- [{title}]({FIG}/{fname})")
    A("")

    A("## Difficulty ladder (easiest → hardest)\n")
    A("| Rating | Route | Tier |")
    A("|:------:|-------|------|")
    for d, name, tier in sorted(all_rows, key=lambda r: (r[0], r[1])):
        A(f"| **{d}** | {name} | {tier} |")
    A("")

    A("## Routes by tier\n")
    notes = {
        "Base — teaching routes":
            "Single-shape routes that introduce one maneuver at a time — the "
            "gentle on-ramp to the warren.",
        "Advanced — creative":
            "Multi-lever routes (gap pinches, pace shifts, two-frequency "
            "terrain, feints) for variety and surprise.",
        "Serious drop":
            "Each built around a committed plunge using the controlled-fall "
            "drift cap — dramatic but not terminal-velocity.",
        "Aggressive drop":
            "Drops that follow the parrot's real gravity arc to ~terminal "
            "velocity (commit-tap then ride). Near-frame-perfect to arrest — "
            "reserve as rare late-game 'boss' moments.",
        "Smaller drop (fair)":
            "Relaxed drops that keep a continuous ≥90px channel (~3 "
            "bird-heights of slack) — sharp but skilled-but-fair.",
    }
    for tier, rows in tiers_data:
        A(f"### {tier}\n")
        if tier in notes:
            A(f"*{notes[tier]}*\n")
        A("| Route | Difficulty | What it teaches / the hook | Length |")
        A("|-------|:----------:|----------------------------|:------:|")
        for d, name, lesson, n, dur in rows:
            A(f"| **{name}** | {d}/10 | {lesson} | {n}p · ~{dur:.0f}s |")
        A("")

    A("## Design notes\n")
    A("- **How long is a warren?** At ~0.45s per pagoda, routes run ~10–29s — a "
      "distinct 'place' you fly through, not a couple of gates. Intense routes "
      "are kept short (~10s) so they thrill rather than exhaust; the medleys run "
      "longest.")
    A("- **Fairness rule.** The forgiving routes guarantee a continuous **≥90px "
      "channel** (~3 bird-heights) the whole way; the aggressive-drop set "
      "deliberately breaks that to reach terminal velocity, which is why it "
      "rates 8–10.")
    A("- **Physics.** Gravity 1600 → terminal 700px/s; one flap rises ~84px. A "
      "downward drop can be far steeper than a climb because the parrot falls "
      "fast on its own — the steepest *fair* drop is a controlled ~80px/pagoda "
      "fall, not the ~136px/pagoda free-fall.")
    A("- **Source.** Routes live in `tools/render_warren_routes*.py`; this "
      "catalogue is generated by `tools/gen_routes_md.py`. No game code is "
      "affected — these are look-dev/design artifacts.")
    A("")

    out = os.path.join("docs", "pagoda_warren", "ROUTES.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out}  ({len(all_rows)} routes)")


if __name__ == "__main__":
    main()
